spring.application.name=sos-service

# Kafka (Producer)
spring.kafka.bootstrap-servers=redpanda:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Server
server.port=8084

# Activate only when profile=docker
spring.config.activate.on-profile=docker
