spring.application.name=sos-service
spring.profiles.active=docker
# Kafka Producer Config
spring.kafka.bootstrap-servers=redpanda:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

#user.service.base-url=http://user-service:8082/api/users/contacts

# Server Port
server.port=8084

