spring.config.activate.on-profile=local

server.port=${SERVER_PORT:8090}

gateway.auth.url=${AUTH_SERVICE_URL:http://localhost:8080}
gateway.user.url=${USER_SERVICE_URL:http://localhost:8082}
gateway.sos.url=${SOS_SERVICE_URL:http://localhost:8084}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.level.root=INFO
logging.level.org.springframework.cloud.gateway=INFO