spring.application.name=user-service
server.port=8082

# Database
spring.datasource.url=jdbc:mysql://mysql-db:3306/userdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=0PMXgqy5njL0FfkYx4nnZyI8FpK0mT5suavPoKygiWiE1NhVjIZ4lLG6FUKxmla
jwt.expiration=3600000

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
logging.level.org.flywaydb=DEBUG

# Kafka
spring.kafka.bootstrap-servers=redpanda:9092
spring.kafka.consumer.group-id=user-service
spring.kafka.consumer.auto-offset-reset=earliest

# Topic name from AuthService
app.user.created.topic=user.identity
app.user.verified.topic=user.verified

# Kafka Consumer (must be active for event mapping)
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Allow deserialization from shared commons package
#spring.kafka.consumer.properties.spring.json.trusted.packages=com.tl.womensafety.common.events

# Ensure Spring uses type headers correctly
#spring.kafka.consumer.properties.spring.json.use.type.headers=true
