apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: womensafety
  labels:
    app: promtail

spec:
  selector:
    matchLabels:
      app: promtail

  template:
    metadata:
      labels:
        app: promtail

    spec:
      serviceAccountName: promtail

      tolerations:
        - operator: Exists

      containers:
        - name: promtail
          image: grafana/promtail:2.9.0

          args:
            - "-config.file=/etc/promtail/config.yaml"

          ports:
            - name: http
              containerPort: 9080

          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          volumeMounts:
            - name: config
              mountPath: /etc/promtail/config.yaml
              subPath: promtail-config.yaml

            - name: positions
              mountPath: /run/promtail

            - name: varlog
              mountPath: /var/log
              readOnly: true
            - mountPath: /var/lib/docker/containers
              name: dockercontainers
              readOnly: true  

      volumes:
        - name: config
          configMap:
            name: promtail-config

        - name: positions
          hostPath:
            path: /var/lib/promtail
            type: DirectoryOrCreate

        - name: varlog
          hostPath:
            path: /var/log

        - hostPath:
            path: /var/lib/docker/containers
          name: dockercontainers    