CREATE TABLE users (
  id BINARY(16) PRIMARY KEY,
  username VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL,
  is_verified TINYINT(1) NOT NULL DEFAULT FALSE
);