spring.application.name=authservice

# Port must match container's exposed port
server.port=8080
server.address=0.0.0.0

# JWT configuration
jwt.secret=0PMXgqy5njL0FfkYx4nnZyI8FpK0mT5suavPoKygiWiE1NhVjIZ4lLG6FUKxmla
jwt.expiration=3600000

# Correct DB connection inside Docker
spring.datasource.url=jdbc:mysql://mysql-db:3306/authdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=user
spring.datasource.password=password
#spring.kafka.bootstrap-servers=localhost:9092
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Format console log and file log with MDC keys
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{userId}] [%X{requestId}] %-5level %logger - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%X{userId}] [%X{requestId}] %-5level %logger - %msg%n

logging.level.org.springdoc=DEBUG


logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.orm.jdbc.bind=WARN

# Logging setup
logging.level.root=INFO
logging.level.com.womensafety.authservice=INFO
logging.file.name=/app/logs/auth-service.log

# ==== OTP settings ====
app.otp.code-length=6
app.otp.ttl-minutes=10
app.otp.max-attempts=5
app.otp.dev-return-code=true

# JPA settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

#spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.acks=all
spring.kafka.producer.retries=10
spring.kafka.producer.retry.backoff.ms=1000

spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5
spring.kafka.producer.properties.delivery.timeout.ms=120000
spring.kafka.producer.properties.linger.ms=5

# our app knobs
app.outbox.poll-ms=2000
app.outbox.batch-size=50
app.user.created.topic=user.identity
app.user.verified.topic=user.verified

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

spring.kafka.bootstrap-servers=redpanda:9092
spring.kafka.consumer.group-id=auth-service-group
spring.kafka.consumer.auto-offset-reset=earliest

app.email.topic=send.email.verification
# Kafka
#spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Topic
app.email.password-reset.topic=send.email.password-reset