apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

  - config/app-config.yaml

  - secrets/app-secrets.yaml

  - infrastructure/mysql.yaml
  - services/auth-service.yaml
  - services/user-service.yaml
  - services/notification-service.yaml
  - services/sos-service.yaml
