apiVersion: v1
kind: Secret
metadata:
  name: womensafety-secrets
  namespace: womensafety

type: Opaque

stringData:
  DB_USERNAME: "user"
  DB_PASSWORD: "password"
  MYSQL_ROOT_PASSWORD: "root"
  JWT_SECRET: "replace_this_with_a_long_random_secret"