spring.application.name=notification-service

# =========================================================
# SERVER
# =========================================================
server.port=${SERVER_PORT:8083}
server.address=0.0.0.0

# =========================================================
# KAFKA
# =========================================================
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP:notification-service-group}
spring.kafka.consumer.auto-offset-reset=${KAFKA_AUTO_OFFSET_RESET:earliest}

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=com.tl.womensafety.common.*,java.util,java.time

spring.kafka.consumer.properties.spring.json.type.mapping=\
EmailVerificationEvent:com.tl.womensafety.common.events.EmailVerificationEvent,\
NotificationRequest:com.tl.womensafety.common.dto.NotificationRequest,\
PasswordResetEvent:com.tl.womensafety.common.events.PasswordResetEvent

# =========================================================
# KAFKA LISTENER
# =========================================================
spring.kafka.listener.ack-mode=${KAFKA_ACK_MODE:record}
spring.kafka.listener.concurrency=${KAFKA_CONCURRENCY:3}

spring.kafka.consumer.max-poll-records=${KAFKA_MAX_POLL_RECORDS:10}

# =========================================================
# EMAIL
# =========================================================
app.email.password-reset.topic=${EMAIL_PASSWORD_RESET_TOPIC:send.email.password-reset}

app.email.mock=${APP_EMAIL_MOCK:true}

# =========================================================
# NOTIFICATION MODE
# =========================================================
notification.mode=${NOTIFICATION_MODE:mock}

# =========================================================
# ACTUATOR
# =========================================================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# =========================================================
# LOGGING
# =========================================================
logging.level.root=INFO
logging.level.org.springframework.kafka=INFO
logging.level.org.apache.kafka=INFO