spring.application.name=notification-service

# Kafka (Docker Run)
spring.kafka.consumer.group-id=notification-service-group
spring.kafka.consumer.auto-offset-reset=earliest

# Server
server.port=8083

logging.level.org.springframework.kafka=DEBUG
logging.level.org.apache.kafka=INFO
notification.mode=mock
#spring.config.import=optional:classpath:application-twilio.properties

spring.kafka.bootstrap-servers=redpanda:9093
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
#spring.kafka.consumer.properties.spring.json.trusted.packages=com.womensafety.notificationservice.events

# Trusted packages
spring.kafka.consumer.properties.spring.json.trusted.packages=com.tl.womensafety.common.*,java.util,java.time
spring.kafka.consumer.properties.spring.json.type.mapping=\
EmailVerificationEvent:com.tl.womensafety.common.events.EmailVerificationEvent,\
NotificationRequest:com.tl.womensafety.common.dto.NotificationRequest,\
PasswordResetEvent:com.tl.womensafety.common.events.PasswordResetEvent

app.email.password-reset.topic=send.email.password-reset
app.email.mock=true

spring.kafka.listener.ack-mode=record
spring.kafka.listener.concurrency=3
spring.kafka.consumer.max-poll-records=10